version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  node-app:
    build: .
    container_name: node-app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/agenda-jobs

volumes:
  mongo-data:
